language: node_js
node_js:
  - "0.10"
before_install:
  - rvm use 1.9.3 --fuzzy
  - export GEMDIR=$(rvm gemdir)
  - which php
  - curl -sS https://getcomposer.org/installer | php
install:
  - time npm install -g grunt-cli bower
  - gem install bundler
  - php composer.phar install
  - bundle
  - bower install
  - npm install
  - grunt ci
