language: php
php:
  - 5.5
  - 5.4
before_install:
  - rvm use 1.9.3 --fuzzy
  - export GEMDIR=$(rvm gemdir)
install:
  - time npm install -g grunt-cli bower
  - gem install bundler
  - bundle
  - composer install
  - bower install
  - npm install
  - grunt ci
script: grunt ci
